# Generated by Django 5.2.5 on 2025-09-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='item_name',
            field=models.CharField(default='new_item', max_length=100),
            preserve_default=False,
        ),
    ]
